### PR TITLE
add vector reflect method

### PR DESCRIPTION
**Pull request by Extrawurst**

### CODE REVIEW

**Comment by Dav1dde** [comment]
This should be a function of math.d

**Comment by Extrawurst** [comment]
i just figured it is the same level as `distance`, `cross` et. al which are right above my reflect inside of linalg.d ?!

**Comment by Extrawurst** [comment]
@Dav1dde looking at math.d those methods there are very generic but imho `reflect` is very specific for vector types in its implementation so it belongs in linalg.d

**Comment by Dav1dde** [comment]
You are right, let me think about it. The idea was putting everything essential to matrices, vectors, quats in linalg.d (e.g. dot product is essential), reflect is more utility, I wanted to put utility into math.d (linalg then publically imports reflect). What do you think of this (current) approach?

**Comment by Extrawurst** [comment]
@Dav1dde I am fine with that approach but I still think distance,cross etc. are misplaced then aswell. i would suggest to accept the PR and change all the methods to math.d then and add a public import.

**Comment by Dav1dde** [comment]
My bad, github doesn't let me merge from my phone...

**Pull request merged**
