### PR TITLE
test latest beta

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by MartinNowak** [comment]
Updated to avoid using a non-working default constructor.

**Comment by MartinNowak** [comment]
> Thanks for the fix, I didnt notice this in the last PR, but shouldn't this be std.compiler.version_major >= 2?

Oh, my mistake, now I understand the `||`.

**Comment by MartinNowak** [comment]
Dropped the commit

**Comment by MartinNowak** [comment]
See https://travis-ci.org/Dav1dde/gl3n/jobs/100831639#L119 for the warning that necessitated the second commit. This was introduced by https://github.com/D-Programming-Language/dmd/pull/5185.

**Comment by Dav1dde** [comment]
Thanks!

**Pull request merged**
